### ISSUE TITLE
Страница со списком YMB-блоков

### ISSUE THREAD

**Issue by avakorin** [itcrowd72/ymb#1]
![image](https://user-images.githubusercontent.com/34230/41811838-dc872eb0-771f-11e8-895b-ffd656ed59af.png)

Предлагаю внести следующие изменения:

1. Название страницы сделать «Блоки сбора средств через Яндекс.Деньги»
2. Отображать колонки
   * block id
   * Название блока (поле «Описание блока» в штатном админ-интерфейсе)
   * Кошелек
   * Назначение платежа
   * Действия

**Comment by itcrowd72** [comment]
Не возражаю

**Comment by itcrowd72** [comment]
Готово
