### ISSUE TITLE
Форма создания YMB-блока

### ISSUE THREAD

**Issue by avakorin** [itcrowd72/ymb#2]
![image](https://user-images.githubusercontent.com/34230/41811885-a4c8f340-7720-11e8-81c5-72d92d32e8bb.png)

1. При создании блока значение поля «Назначение платежа» копировать в штатное поле «Заголовок блока».
2. При создании блока значение поля «Назначение платежа» копировать в поле «Описание блока» в формате «YMB: %назначение_платежа (block_id)%»
3. Название поля «Назначение платежа (текст)» заменить на «Назначение платежа».
4. Название поля «Сумма платежа (по-умолчанию)» заменить на «Сумма платежа по-умолчанию»

**Comment by itcrowd72** [comment]
Будет сделано

**Comment by itcrowd72** [comment]
Готово
