### ISSUE TITLE
Отображение YMB-блока пользователям

### ISSUE THREAD

**Issue by avakorin** [itcrowd72/ymb#5]
![image](https://user-images.githubusercontent.com/34230/41811999-e7e1a864-7722-11e8-8364-391ad55fad72.png)

1. Думаю, нужно написать текст в именительном падеже:
«Яндекс.Деньги»
«Банковская карта»

2. И переименовать кнопку в «Оплатить».

**Comment by itcrowd72** [comment]
Согласен

**Comment by itcrowd72** [comment]
Готово
